# 部署：~/.config/tmux/tmux.conf

# 窗口从1开始
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# 免前缀：Shift+左右方向键，切上一个/下一个窗口
bind -n S-Left  previous-window
bind -n S-Right next-window


